/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcu.h"


void
calculadora_1(char *host, int opc)
{
	CLIENT *clnt;
	float  *result_1;
	entrada  suma_1_arg;
	float  *result_2;
	entrada  resta_1_arg;
	float  *result_3;
	entrada  multiplicacion_1_arg;
	float  *result_4;
	entrada  division_1_arg;
	if(opc==1){
	printf("============================\n");
	printf("Digite los elementos a sumar \n a: ");
	scanf("%f", &suma_1_arg.arg1);
	printf(" b: ");
	scanf("%f", &suma_1_arg.arg2);
	
	}
	else if(opc==2){
	printf("============================\n");
	printf("Digite los elementos a restar \n a: ");
	scanf("%f", &resta_1_arg.arg1);
	printf(" b: ");
	scanf("%f", &resta_1_arg.arg2);
	}
	else if(opc==3){
	printf("============================\n");
	printf("Digite los elementos a multiplicar \n a: ");
	scanf("%f", &multiplicacion_1_arg.arg1);
	printf(" b: ");
	scanf("%f", &multiplicacion_1_arg.arg2);
	}
	else if(opc==4){
	printf("============================\n");
	printf("Digite los elementos a dividir \n a: ");
	scanf("%f", &division_1_arg.arg1);
	printf(" b: ");
	scanf("%f", &division_1_arg.arg2);
	}

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, CALCULADORA_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = suma_1(&suma_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = resta_1(&resta_1_arg, clnt);
	if (result_2 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = multiplicacion_1(&multiplicacion_1_arg, clnt);
	if (result_3 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = division_1(&division_1_arg, clnt);
	if (result_4 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

	if(opc==1){
	printf("============================\n");
	printf("\n Suma = (%.2f + %.2f) = %.2f\n\n",
	suma_1_arg.arg1, suma_1_arg.arg2, *result_1);
	printf("============================\n");
	}
	else if(opc==2){
	printf("============================\n");
	printf("\n Resta = (%.2f - %.2f) = %.2f\n\n",
	resta_1_arg.arg1, resta_1_arg.arg2, *result_2);
	printf("============================\n");
	}
	else if(opc==3){
	printf("============================\n");
	printf("\n Multiplicacion = (%.2f * %.2f) = %.2f\n\n",
	multiplicacion_1_arg.arg1, multiplicacion_1_arg.arg2, *result_3);
	printf("============================\n");
	}
	else if(opc==4){
	printf("============================\n");
	printf("\n Division = (%.2f / %.2f) = %.2f\n\n",
	division_1_arg.arg1, division_1_arg.arg2, *result_4);
	printf("============================\n");
	}
	
}


int
main (int argc, char *argv[])
{
	char *host;
	int r;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	printf("============================\n");
	printf("	CALCULADORA RPC \n");
	printf("============================\n");
	printf("Selecciona la Operacion\n");
	printf(" 1- Suma\n 2- Resta \n 3- Multiplicacion \n 4- Division \n");
	scanf("%d",&r);
	
	
	host = argv[1];
	calculadora_1 (host, r);
exit (0);
}
