/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcu.h"

float *
suma_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * resultado
	 */
	 operacion oper;
	 oper.resultado=argp->arg1 + argp->arg2;
	 result= oper.resultado;
	 
	 oper.op.arg1 = argp->arg1;
	 oper.op.arg2 = argp->arg2;
	 oper.resultado = result;

	return &result;
}

float *
resta_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * resultado
	 */
	operacion oper;
	oper.resultado=argp->arg1 - argp->arg2;
	result= oper.resultado;
	 
	oper.op.arg1 = argp->arg1;
	oper.op.arg2 = argp->arg2;
	oper.resultado = result; 
	 
	

	return &result;
}

float *
multiplicacion_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * resultado
	 */

	operacion oper;
	oper.resultado=argp->arg1 * argp->arg2;
	result= oper.resultado;
	 
	oper.op.arg1 = argp->arg1;
	oper.op.arg2 = argp->arg2;
	oper.resultado = result; 

	return &result;
}

float *
division_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * resultado
	 */
	 
	operacion oper;
	oper.resultado=argp->arg1 / argp->arg2;
	result= oper.resultado;
	 
	oper.op.arg1 = argp->arg1;
	oper.op.arg2 = argp->arg2;
	oper.resultado = result; 

	return &result;
}
